Fix newMockFirebaseApp() throwing IAE due to a new "Deferred<InternalAuthProvider>" parameter added to the FirebaseDataConnectFactory constructor.
This fixes test failures in PostsConnectorUnitTest, such as:

java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0()
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance()
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance()
	at java.base/java.lang.reflect.Constructor.newInstance()
	at com.google.firebase.dataconnect.testutil.FirebaseDataConnectTestUtilKt.newMockFirebaseApp$lambda-0()
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer()
	at org.mockito.internal.handler.MockHandlerImpl.handle()
	at org.mockito.internal.handler.NullResultGuardian.handle()
	at org.mockito.internal.handler.InvocationNotifierHandler.handle()
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept()
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept()
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable()
	at com.google.firebase.FirebaseApp$MockitoMock$1168607441.get()
	at com.google.firebase.dataconnect.FirebaseDataConnectKt.getInstance()
	at com.google.firebase.dataconnect.FirebaseDataConnectKt.getInstance$default()
	at com.google.firebase.dataconnect.connectors.PostsConnector$Companion.getInstance()
	at com.google.firebase.dataconnect.PostsConnectorUnitTest$posts$2.invoke()
	at com.google.firebase.dataconnect.PostsConnectorUnitTest$posts$2.invoke()
	at kotlin.SynchronizedLazyImpl.getValue()
	at com.google.firebase.dataconnect.PostsConnectorUnitTest.getPosts()
	at com.google.firebase.dataconnect.PostsConnectorUnitTest.createComment property should always return the same instance()