Update sessions-e2e.yml
name: Firebase Sessions E2E Tests

on:
  schedule:
    - cron: 24 */4 * * *  # every 4 hours at 24 minutes past the hour
  workflow_dispatch:     # allow triggering the workflow manually

concurrency:
  group: ${{ github.workflow }}

env:
  SESSIONS_E2E_GOOGLE_SERVICES: ${{ secrets.SESSIONS_E2E_GOOGLE_SERVICES }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout firebase-sessions
        uses: actions/checkout@v3.5.3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Add google-services.json
        run: |
          echo $SESSIONS_E2E_GOOGLE_SERVICES | base64 -d > google-services.json

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v0
      - name: Run sessions end-to-end tests
        env:
          FTL_RESULTS_BUCKET: fireescape
        run: |
          - check: gradlew/firebase-sessions:test-app:device Check with Error Prone -PtargetBackend="prod"
- name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.3
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional