Downgrade com.google.gms:google-services back to 4.3.15, since 4.4.2 appear to break firestore
The Firestore build error is 

```
firestore/src/androidTest/java/com/google/firebase/firestore/testutil/prod_provider/FirestoreProvider.java:39: error: cannot find symbol
    return context.getString(R.string.project_id);
                              ^
  symbol:   variable string
  location: class R
```