Migrating to new protolite runtime (#1534)
* Upgrade Firestore's GRPC to 1.26

* Bump prolite GRPC version

* fix other callers

* remove javalite

* Use the same Guava

* Google truth

* GRPC testing

* Fix

* ...

* fix iam

* fix firestore

* More attempts that failed

* WIP

* grpc & protobuf-javalite

* Fix components & installations gradle error in fiamui-app.

* Moving back to proto

* Removing grpc protos

* 1

* Fixing smoke tests

* Fixing smoke tests

* Test

* test2

* Cherry picking cloud protos

* Descriptor

* Cleanup

* 1. No proto deps

Failure
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258819568042774532/
google/firestore/v1/document.proto:20:1: Import "google/api/annotations.proto" was not found or had errors.
google/firestore/v1/document.proto:23:1: Import "google/type/latlng.proto" was not found or had errors.
google/firestore/v1/document.proto:123:5: "google.type.LatLng" is not defined.
google/firebase/firestore/proto/maybe_document.proto:24:1: Import "google/firestore/v1/document.proto" was not found or had errors.
google/firebase/firestore/proto/maybe_document.proto:57:5: "google.firestore.v1.Document" is not defined.

* 2. Adding only cloud protos

Smoke test failures
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258800815649329152/

* 3. Upgrading proto toolchain

Since the cloud protos brings in the proto dep, the resulting well known types has conflicting classes
Failures
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258860209397305345/
 java.lang.RuntimeException: Duplicate class com.google.protobuf.Any found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)
  Duplicate class com.google.protobuf.Any$1 found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)
  Duplicate class com.google.protobuf.Any$Builder found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)
  Duplicate class com.google.protobuf.AnyOrBuilder found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)

* 4. Excluded proto dependencies

Descriptor not found
Smoke test failures
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258862867042537472/

* Added compile(only?) dep on proto

Smoke test failures
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258867395951333376/

* Vendored descriptor proto

Duplicate classes
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258872300619436032/

* Removed proto compile dep
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258873811042832387/

* Removed duration

https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258877965266063361/

* Added duration as a `protobuf` config

* Removing duration class files

* Changing case

* Bumped version of well known types

* Use previous version of GRPC because of guava dep.

* Changes to transport-backend-cct proto configuration.

* remove fiamui-app

* remove fiamu-app entry in subprojects.cfg

* testapp fix

* Use full proto runtime for tests.

* Use same protoc version for all entries.

* Don't upgrade version for crashlytics tests.

* Proguard rule for inappmessaging.

* Test using protobuf only

* Rollback previous test.

* Move proguard to well-known-types.

* Use javalite fix referred in protobuf repo

https://github.com/protocolbuffers/protobuf/issues/7094#issuecomment-637044968

* Propagate proguart configuration from protolite-well-known-types

* Nit, fixes, and clean ups.

* Use double quotes for variable substitution.

* Missing 'c'

* Remove unwanted change.

* Additional lints.

* No javadoc for protolite-well-known-types.

* Undo changes to protolite-well-known-types

* Add empty api.txt

* Don't publish javadoc for proto-well-known-types.

* Address comments.

Co-authored-by: Sebastian Schmidt <mrschmidt@google.com>
Co-authored-by: Rodrigo Lazo Paz <rlazo@google.com>