Safely handle unbinding service connection (#5884)
Fix for #5869.

`Fatal Exception: java.lang.IllegalArgumentException: Service not
registered: [obfuscated]` happens when the context calls `unbindService`
on a service connection that has not been bounded. Either due to
`SecurityException` or the existing service cannot be found from the map
of services that has been bounded.

Simulating tests by calling `unbindService` without initially calling
`bindService` will result to the same stacktrace as with the issue:
```
java.lang.IllegalArgumentException: Service not registered: com.example.testunbinding.MainActivity$onCreate$serviceConnection$1@8988566
                                                                                                    	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
                                                                                                    	at android.app.ContextImpl.unbindService(ContextImpl.java:1511)
                                                                                                    	at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
                                                                                                    	at com.example.testunbinding.MainActivity.onCreate$lambda$0(MainActivity.kt:48)
                                                                                                    	at com.example.testunbinding.MainActivity.$r8$lambda$mcIw03Dd4PpO0vDw0ScUjxsazkw(MainActivity.kt)
                                                                                                    	at com.example.testunbinding.MainActivity$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
```

I've verified that the try-catch for `IllegalArgumentException` works.