3. Upgrading proto toolchain
Since the cloud protos brings in the proto dep, the resulting well known types has conflicting classes
Failures
https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/1534/smoke-tests/1258860209397305345/
 java.lang.RuntimeException: Duplicate class com.google.protobuf.Any found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)
  Duplicate class com.google.protobuf.Any$1 found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)
  Duplicate class com.google.protobuf.Any$Builder found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)
  Duplicate class com.google.protobuf.AnyOrBuilder found in modules classes.jar (com.google.firebase:protolite-well-known-types:17.0.1-SNAPSHOT:20200508.204735-1) and protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)