QuerySubscriptionImplUnitTest.kt: fix spurious failures in testNetworkConnectivityRestoration() when there is a delay before killing the physical connection after last subscriber unsubscribes.
Although the test is passing, specifying a non-zero value for the
`stopTimeoutMillis` parameter to `SharingStarted.WhileSubscribed()` in
`DataConnectBidiConnectStream.kt` causes the following spurious failure:

```
TurbineAssertionError: Unconsumed events found for serverCollector:
 - Item(ErrorReceived(ConnectionId(value=NNNN), StatusRuntimeException(CANCELLED: client cancelled, code=CANCELLED)))
  at app.cash.turbine.TurbineAssertionError$Companion.invoke(TurbineAssertionError.kt:32)
  at app.cash.turbine.ChannelTurbine.ensureAllEventsConsumed(Turbine.kt:246)
  ...
  at QuerySubscriptionImplUnitTest.testNetworkConnectivityRestoration(QuerySubscriptionImplUnitTest.kt:1639)
  at QuerySubscriptionImplUnitTest.network connectivity restoration resets backoff delay to initial value(QuerySubscriptionImplUnitTest.kt:1611)
```

This commit fixes the spurious error by consuming the expected
disconnect event that will eventually arrive. The following 2 tests are
fixed by this change:

* `network connectivity restoration resets backoff delay to initial value`
* `network connectivity restoration resets retries immediately`